export const GET_PLACE_DETAILS = "GET_PLACE_DETAILS";
export const SET_SELECTED_PLACE = "SET_SELECTED_PLACE";
export const SET_SEARCH_HISTORY = "SET_SEARCH_HISTORY";
export const RESET_SEARCH_HISTORY = "RESET_SEARCH_HISTORY";

